name: Daka Auto Sign

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '40 0 * * *'  # UTC +8，这里设置的早上9点10分运行
    - cron: '55 10 * * *' # UTC +8，这里设置的晚上18点55分运行
    - cron: '10 14 * * *' # UTC +8，这里设置的晚上22点10分运行
    - cron: '30 16 * * *' # UTC +8，这里设置的晚上23点30分运行
jobs:
  Daka:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install Playwright dependencies
      run: |
        sudo npx playwright install-deps

    - name: Set up Chrome and Chromedriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 'latest'

    - name: Install Playwright browsers
      run: |
        python -m playwright install

    - name: Run
      run: |
        python -m daka -v ${{secrets.MAX_PAGE}} ${{secrets.UPLOAD_URL}} ${{secrets.OSS_KEY_ID}} ${{secrets.OSS_ACCESS_KEY}} ${{secrets.OSS_BUCKET_NAME}} ${{secrets.OSS_UID}}